# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 855)
        MainWindow.setStyleSheet("*{\n"
"background-color:#09c;\n"
"padding:0px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exercises = QtWidgets.QPushButton(self.centralwidget)
        self.exercises.setGeometry(QtCore.QRect(0, 110, 221, 51))
        self.exercises.setStyleSheet("*{\n"
"background-color:#708090;\n"
"color:#FFFFFF;\n"
"border:0px;\n"
"}\n"
"\n"
"*:hover{\n"
"background-color:#0f9d9a;\n"
"color:#FFFFFF;\n"
"}")
        self.exercises.setObjectName("exercises")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 0, 221, 861))
        self.listView.setMinimumSize(QtCore.QSize(0, 621))
        self.listView.setStyleSheet("*{\n"
"background-color:#708090;\n"
"height:100px;\n"
"\n"
"}")
        self.listView.setMovement(QtWidgets.QListView.Free)
        self.listView.setProperty("isWrapping", True)
        self.listView.setResizeMode(QtWidgets.QListView.Adjust)
        self.listView.setObjectName("listView")
        self.userInfo = QtWidgets.QPushButton(self.centralwidget)
        self.userInfo.setGeometry(QtCore.QRect(0, 170, 221, 51))
        self.userInfo.setStyleSheet("*{\n"
"background-color:#708090;\n"
"color:#FFFFFF;\n"
"border:0px;\n"
"}\n"
"\n"
"*:hover{\n"
"background-color:#0f9d9a;\n"
"color:#FFFFFF;\n"
"}")
        self.userInfo.setObjectName("userInfo")
        self.history = QtWidgets.QPushButton(self.centralwidget)
        self.history.setGeometry(QtCore.QRect(0, 220, 221, 51))
        self.history.setStyleSheet("*{\n"
"background-color:#708090;\n"
"color:#FFFFFF;\n"
"border:0px;\n"
"}\n"
"\n"
"*:hover{\n"
"background-color:#0f9d9a;\n"
"color:#FFFFFF;\n"
"}")
        self.history.setObjectName("history")
        self.achievements = QtWidgets.QPushButton(self.centralwidget)
        self.achievements.setGeometry(QtCore.QRect(0, 270, 221, 51))
        self.achievements.setStyleSheet("*{\n"
"background-color:#708090;\n"
"color:#FFFFFF;\n"
"border:0px;\n"
"}\n"
"\n"
"*:hover{\n"
"background-color:#0f9d9a;\n"
"color:#FFFFFF;\n"
"}")
        self.achievements.setObjectName("achievements")
        self.EXIT = QtWidgets.QPushButton(self.centralwidget)
        self.EXIT.setGeometry(QtCore.QRect(0, 330, 221, 51))
        self.EXIT.setStyleSheet("*{\n"
"background-color:#708090;\n"
"color:#FFFFFF;\n"
"border:0px;\n"
"}\n"
"\n"
"*:hover{\n"
"background-color:#0f9d9a;\n"
"color:#FFFFFF;\n"
"}")
        self.EXIT.setObjectName("EXIT")
        self.exFrame = QtWidgets.QFrame(self.centralwidget)
        self.exFrame.setGeometry(QtCore.QRect(210, -10, 921, 871))
        self.exFrame.setStyleSheet("background-color:white;\n"
"display:none;")
        self.exFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exFrame.setObjectName("exFrame")
        self.label = QtWidgets.QLabel(self.exFrame)
        self.label.setGeometry(QtCore.QRect(200, 30, 191, 61))
        self.label.setStyleSheet("font-weight:900;\n"
"background-color:gray;")
        self.label.setObjectName("label")
        self.usframe = QtWidgets.QFrame(self.exFrame)
        self.usframe.setGeometry(QtCore.QRect(0, -20, 911, 621))
        self.usframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.usframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.usframe.setObjectName("usframe")
        self.hisframe = QtWidgets.QFrame(self.usframe)
        self.hisframe.setGeometry(QtCore.QRect(10, 30, 911, 611))
        self.hisframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hisframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hisframe.setObjectName("hisframe")
        self.label_4 = QtWidgets.QLabel(self.hisframe)
        self.label_4.setGeometry(QtCore.QRect(230, 30, 91, 41))
        self.label_4.setStyleSheet("background-color:gray;")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.hisframe)
        self.label_3.setGeometry(QtCore.QRect(220, 30, 101, 51))
        self.label_3.setStyleSheet("background-color:gray;")
        self.label_3.setObjectName("label_3")
        self.achFrame = QtWidgets.QFrame(self.hisframe)
        self.achFrame.setGeometry(QtCore.QRect(-10, 0, 911, 851))
        self.achFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.achFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.achFrame.setObjectName("achFrame")
        self.label_5 = QtWidgets.QLabel(self.achFrame)
        self.label_5.setGeometry(QtCore.QRect(410, 50, 131, 41))
        self.label_5.setStyleSheet("background-color:transparent;\n"
"border:1px solid;")
        self.label_5.setObjectName("label_5")
        self.listView_2 = QtWidgets.QListView(self.achFrame)
        self.listView_2.setGeometry(QtCore.QRect(40, 140, 851, 141))
        self.listView_2.setObjectName("listView_2")
        self.label_6 = QtWidgets.QLabel(self.achFrame)
        self.label_6.setGeometry(QtCore.QRect(730, 150, 131, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.achFrame)
        self.label_7.setGeometry(QtCore.QRect(750, 250, 101, 21))
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.achFrame)
        self.label_10.setGeometry(QtCore.QRect(750, 210, 81, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.achFrame)
        self.label_11.setGeometry(QtCore.QRect(770, 180, 55, 21))
        self.label_11.setObjectName("label_11")
        self.label_2 = QtWidgets.QLabel(self.exFrame)
        self.label_2.setGeometry(QtCore.QRect(50, 160, 161, 121))
        self.label_2.setStyleSheet("border-radius:60px;\n"
"background-color:gray;")
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.exFrame)
        self.label_8.setGeometry(QtCore.QRect(450, 200, 55, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.exFrame)
        self.label_9.setGeometry(QtCore.QRect(400, 160, 151, 41))
        self.label_9.setObjectName("label_9")
        self.exFrame.raise_()
        self.listView.raise_()
        self.exercises.raise_()
        self.userInfo.raise_()
        self.history.raise_()
        self.achievements.raise_()
        self.EXIT.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exercises.setText(_translate("MainWindow", "Exercises"))
        self.userInfo.setText(_translate("MainWindow", "Show User Info"))
        self.history.setText(_translate("MainWindow", "History"))
        self.achievements.setText(_translate("MainWindow", "Achievements"))
        self.EXIT.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Exercises</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">History</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">User Info</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Achievements</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Best Score</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">21/3/2022</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Date</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">0</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Image</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Name</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Exercise name</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
