# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rpframe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from datetime import datetime

from PyQt5 import QtCore, QtGui, QtWidgets


import Calories_calculator

import pickle

from Database import DBoperation


class Ui_Form(object):
    Trainingname = ''
    Rmtime = datetime.now()
    Repscount = 0

    def __init__(self,Trainingname,Rmtime,Repscount):
        self.Trainingname=Trainingname
        self.Repscount=Repscount
        self.Rmtime=Rmtime


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1140, 820)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, -10, 1140, 833))
        self.frame.setStyleSheet("#frame{\n"
"background-image: url(\'report.jpg\');\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 341, 831))
        self.frame_2.setStyleSheet("background-color :#10101a")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(90, 30, 200, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color :white")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")

        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 220, 321, 291))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_4.setStyleSheet("*{\n"
                                    "background-color:#1a1a29;\n"
                                    "color:#FFFFFF;\n"
                                    "border:0px;\n"
                                    "}\n"
                                    "\n"
                                    "*:hover{\n"
                                    "background-color:;\n"
                                    "color:#FFFFFF;\n"
                                    "}")

        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(380, 450, 221, 51))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_2.setGeometry(QtCore.QRect(630, 450, 221, 51))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_3.setGeometry(QtCore.QRect(880, 450, 221, 51))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setFont(font)
        self.textEdit_3.setFont(font)
        self.textEdit_2.setFont(font)

        self.textEdit_4.setFont(font)
        self.textEdit_4.setEnabled(False)
        self.textEdit.setEnabled(False)
        self.textEdit_2.setEnabled(False)
        self.textEdit_3.setEnabled(False)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Training name "))
        self.label.setText(self.Trainingname)
        self.textEdit_2.setText(str(self.Rmtime))
        self.textEdit_3.setText(str(self.Repscount))
        calories, cal_information = Calories_calculator.Cl_cal(self.Trainingname,self.Repscount,self.Rmtime)
        self.textEdit_4.setText(cal_information)
        self.textEdit.setText(str(calories))
        f = open('store.pckl', 'rb')
        obj = pickle.load(f)
        DBoperation.database_operations.insertBestScore(self.Trainingname, str(obj[0]), self.Repscount, 'work')
        f.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
