# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BMI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    Height = 172
    Weight = 76
    BMI = 0
    comment = ""
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(2000, 1000)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.MainFrame = QtWidgets.QFrame(Dialog)
        self.MainFrame.setGeometry(QtCore.QRect(0, 0, 2000, 841))
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.frame_2 = QtWidgets.QFrame(self.MainFrame)
        self.frame_2.setGeometry(QtCore.QRect(80, 60, 1161, 761))
        self.frame_2.setStyleSheet("background-color:#7996C3;\n"
"\n"
"QPushButton{\n"
" background-color: #333333;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(190, 290, 761, 291))
        self.frame.setStyleSheet("background-color:#042940;\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 30, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.height = QtWidgets.QLabel(self.frame)
        self.height.setGeometry(QtCore.QRect(70, 70, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.height.setFont(font)
        self.height.setStyleSheet("color: rgb(255, 255, 255);")
        self.height.setAlignment(QtCore.Qt.AlignCenter)
        self.height.setObjectName("height")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(320, 30, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.weight = QtWidgets.QLabel(self.frame)
        self.weight.setGeometry(QtCore.QRect(310, 70, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.weight.setFont(font)
        self.weight.setStyleSheet("color: rgb(255, 255, 255);")
        self.weight.setAlignment(QtCore.Qt.AlignCenter)
        self.weight.setObjectName("weight")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(550, 30, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(550, 70, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.weight_2 = QtWidgets.QLabel(self.frame)
        self.weight_2.setGeometry(QtCore.QRect(210, 140, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.weight_2.setFont(font)
        self.weight_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.weight_2.setAlignment(QtCore.Qt.AlignCenter)
        self.weight_2.setObjectName("weight_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1161, 261))
        self.frame_3.setStyleSheet("background-color: #03416E;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(390, 120, 451, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.frame_3.raise_()
        self.frame.raise_()
        self.calculateBMI()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "height ( in cm )"))
        self.height.setText(_translate("Dialog", str(self.Height)+" Cm"))
        self.label_10.setText(_translate("Dialog", "weight (in kg)"))
        self.weight.setText(_translate("Dialog", str(self.Weight)+" Kg"))
        self.label_12.setText(_translate("Dialog", "BMI"))
        self.label_13.setText(_translate("Dialog", str(round(self.BMI,2))))

        self.weight_2.setText(_translate("Dialog", self.comment))

        self.label.setText(_translate("Dialog", "Body mass index (BMI)"))
    def calculateBMI(self):
        self.BMI = self.Weight / (self.Height / 100) ** 2
        if self.BMI <= 18.4:
            self.comment="You are underweight."
        elif self.BMI <= 24.9:
            self.comment="You are healthy."
        elif self.BMI <= 29.9:
            self.comment ="You are over weight."
        elif self.BMI <= 34.9:
            self.comment="You are severely over weight."
        elif self.BMI <= 39.9:
            self.comment="You are obese."
        else:
            self.comment ="You are severely obese."


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
